
package com.qijianguo.service.webservice.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomWebService", targetNamespace = "http://www.CustomWebService.service.qijianguo.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomWebService {


    /**
     * 
     * @param feedback
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "String", targetNamespace = "")
    @RequestWrapper(localName = "feedback", targetNamespace = "http://www.CustomWebService.service.qijianguo.com", className = "com.qijianguo.service.webservice.server.Feedback")
    @ResponseWrapper(localName = "feedbackResponse", targetNamespace = "http://www.CustomWebService.service.qijianguo.com", className = "com.qijianguo.service.webservice.server.FeedbackResponse")
    public String feedback(
        @WebParam(name = "feedback", targetNamespace = "")
        String feedback);

}
