
package com.qijianguo.service.webservice.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomWebService", targetNamespace = "http://www.CustomWebService.service.qijianguo.com", wsdlLocation = "http://localhost:8080/services/CustomWebService?wsdl")
public class CustomWebService_Service
    extends Service
{

    private final static URL CUSTOMWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMWEBSERVICE_EXCEPTION;
    private final static QName CUSTOMWEBSERVICE_QNAME = new QName("http://www.CustomWebService.service.qijianguo.com", "CustomWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/CustomWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMWEBSERVICE_WSDL_LOCATION = url;
        CUSTOMWEBSERVICE_EXCEPTION = e;
    }

    public CustomWebService_Service() {
        super(__getWsdlLocation(), CUSTOMWEBSERVICE_QNAME);
    }

    public CustomWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMWEBSERVICE_QNAME, features);
    }

    public CustomWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMWEBSERVICE_QNAME);
    }

    public CustomWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMWEBSERVICE_QNAME, features);
    }

    public CustomWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomWebService
     */
    @WebEndpoint(name = "CustomWebServiceImplPort")
    public CustomWebService getCustomWebServiceImplPort() {
        return super.getPort(new QName("http://www.CustomWebService.service.qijianguo.com", "CustomWebServiceImplPort"), CustomWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomWebService
     */
    @WebEndpoint(name = "CustomWebServiceImplPort")
    public CustomWebService getCustomWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.CustomWebService.service.qijianguo.com", "CustomWebServiceImplPort"), CustomWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMWEBSERVICE_EXCEPTION!= null) {
            throw CUSTOMWEBSERVICE_EXCEPTION;
        }
        return CUSTOMWEBSERVICE_WSDL_LOCATION;
    }

}
