<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.CustomWebService.service.qijianguo.com" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="CustomWebService" targetNamespace="http://www.CustomWebService.service.qijianguo.com">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.CustomWebService.service.qijianguo.com" elementFormDefault="unqualified" targetNamespace="http://www.CustomWebService.service.qijianguo.com" version="1.0">

  <xs:element name="feedback" type="tns:feedback"/>

  <xs:element name="feedbackResponse" type="tns:feedbackResponse"/>

  <xs:complexType name="feedback">
    <xs:sequence>
      <xs:element minOccurs="0" name="feedback" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="feedbackResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="String" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="feedbackResponse">
    <wsdl:part element="tns:feedbackResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="feedback">
    <wsdl:part element="tns:feedback" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="CustomWebService">
    <wsdl:operation name="feedback">
      <wsdl:input message="tns:feedback" name="feedback">
    </wsdl:input>
      <wsdl:output message="tns:feedbackResponse" name="feedbackResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CustomWebServiceSoapBinding" type="tns:CustomWebService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="feedback">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="feedback">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="feedbackResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CustomWebService">
    <wsdl:port binding="tns:CustomWebServiceSoapBinding" name="CustomWebServiceImplPort">
      <soap:address location="http://localhost:8080/services/CustomWebService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>