package com.qijianguo.dao;

import com.qijianguo.dataobject.ItemDo;
import com.qijianguo.dataobject.ItemDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    List<ItemDo> selectByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    ItemDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int updateByPrimaryKey(ItemDo record);

    List<ItemDo> listItem();

    int increaseSales(@Param("itemId") Integer itemId, @Param("amount") Integer amount);

}