package com.qijianguo.dao;

import com.qijianguo.dataobject.ItemStockDo;
import com.qijianguo.dataobject.ItemStockDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemStockDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int insert(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int insertSelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    List<ItemStockDo> selectByExample(ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    ItemStockDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Wed Feb 20 09:40:07 CST 2019
     */
    int updateByPrimaryKey(ItemStockDo record);

    ItemStockDo selectByItemId(Integer id);

    int decreaseStock(@Param("amount") Integer amount, @Param("itemId") Integer itemId);
}