package com.qijianguo.dao;

import com.qijianguo.dataobject.OrderInfoDo;
import com.qijianguo.dataobject.OrderInfoDoExample;
import java.util.List;

public interface OrderInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Feb 20 15:21:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Feb 20 15:21:27 CST 2019
     */
    int insert(OrderInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Feb 20 15:21:27 CST 2019
     */
    int insertSelective(OrderInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Feb 20 15:21:27 CST 2019
     */
    List<OrderInfoDo> selectByExample(OrderInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Feb 20 15:21:27 CST 2019
     */
    OrderInfoDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Feb 20 15:21:27 CST 2019
     */
    int updateByPrimaryKeySelective(OrderInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Feb 20 15:21:27 CST 2019
     */
    int updateByPrimaryKey(OrderInfoDo record);
}