package com.qijianguo.dao;

import com.qijianguo.dataobject.SequenceInfoDo;
import com.qijianguo.dataobject.SequenceInfoDoExample;
import java.util.List;

public interface SequenceInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Feb 20 16:34:42 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Feb 20 16:34:42 CST 2019
     */
    int insert(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Feb 20 16:34:42 CST 2019
     */
    int insertSelective(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Feb 20 16:34:42 CST 2019
     */
    List<SequenceInfoDo> selectByExample(SequenceInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Feb 20 16:34:42 CST 2019
     */
    SequenceInfoDo selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Feb 20 16:34:42 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Feb 20 16:34:42 CST 2019
     */
    int updateByPrimaryKey(SequenceInfoDo record);

    SequenceInfoDo selectByName(String name);
}